In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [3]:
#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [4]:
#Launch th graph in a session
sess = tf.Session()
#Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val,_ = sess.run([cost, hypothesis, train],
                                 feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  12359.786 
Prediction:
 [259.24976 296.54462 300.04196 325.85385 223.1303 ]
10 Cost:  45.265903 
Prediction:
 [161.05766 178.57413 183.77812 199.24815 133.15852]
20 Cost:  44.91096 
Prediction:
 [160.73473 178.23492 183.41846 198.85916 132.90976]
30 Cost:  44.669933 
Prediction:
 [160.70796 178.2516  183.4095  198.8521  132.93242]
40 Cost:  44.430283 
Prediction:
 [160.68216 178.2693  183.40163 198.84619 132.95581]
50 Cost:  44.191944 
Prediction:
 [160.65645 178.28696 183.39375 198.84029 132.97914]
60 Cost:  43.954773 
Prediction:
 [160.63078 178.30457 183.38591 198.83441 133.00243]
70 Cost:  43.719055 
Prediction:
 [160.60521 178.32213 183.37811 198.82857 133.02563]
80 Cost:  43.484535 
Prediction:
 [160.57971 178.33965 183.37032 198.82274 133.0488 ]
90 Cost:  43.251324 
Prediction:
 [160.55426 178.3571  183.36256 198.81693 133.07188]
100 Cost:  43.019306 
Prediction:
 [160.52888 178.37451 183.3548  198.8111  133.09491]
110 Cost:  42.78858 
Prediction:
 [160.50357 178.39186 

1100 Cost:  25.157106 
Prediction:
 [158.31036 179.89745 182.67761 198.30101 135.11055]
1110 Cost:  25.022861 
Prediction:
 [158.29109 179.91069 182.67174 198.29655 135.1281 ]
1120 Cost:  24.889452 
Prediction:
 [158.27188 179.92389 182.6659  198.29213 135.14558]
1130 Cost:  24.756672 
Prediction:
 [158.25269 179.93703 182.66    198.28769 135.16301]
1140 Cost:  24.624561 
Prediction:
 [158.23357 179.95016 182.65417 198.28326 135.18042]
1150 Cost:  24.493252 
Prediction:
 [158.2145  179.96326 182.64836 198.27885 135.19775]
1160 Cost:  24.362604 
Prediction:
 [158.19548 179.97632 182.64255 198.27446 135.21506]
1170 Cost:  24.23264 
Prediction:
 [158.17653 179.98936 182.63678 198.27008 135.23233]
1180 Cost:  24.10347 
Prediction:
 [158.15762 180.00235 182.63101 198.26575 135.24954]
1190 Cost:  23.974955 
Prediction:
 [158.13875 180.01527 182.62526 198.26134 135.2667 ]
1200 Cost:  23.847136 
Prediction:
 [158.11993 180.02818 182.61952 198.257   135.28381]
1210 Cost:  23.719913 
Prediction: