In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]
#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [3]:
#Hypothesis
hypothesis = tf.matmul(X, W) + b#cf) matmul은 "Multiplies matrix a by matrix b"
#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [4]:
#Launch the graph in a session
sess = tf.Session()
#Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  44706.117 
Prediction:
 [[-34.17025 ]
 [-42.372513]
 [-41.12476 ]
 [-43.488556]
 [-33.846603]]
10 Cost:  5.9111686 
Prediction:
 [[152.85226]
 [182.42908]
 [180.3686 ]
 [197.71246]
 [137.62376]]
20 Cost:  5.4791937 
Prediction:
 [[153.41052]
 [183.11453]
 [181.0365 ]
 [198.4401 ]
 [138.14993]]
30 Cost:  5.456585 
Prediction:
 [[153.40463]
 [183.12186]
 [181.03625]
 [198.44012]
 [138.15884]]
40 Cost:  5.4340606 
Prediction:
 [[153.39705]
 [183.12712]
 [181.03401]
 [198.43799]
 [138.16621]]
50 Cost:  5.411689 
Prediction:
 [[153.38948]
 [183.13235]
 [181.03178]
 [198.43584]
 [138.17354]]
60 Cost:  5.3894234 
Prediction:
 [[153.38194]
 [183.13757]
 [181.02953]
 [198.43367]
 [138.18083]]
70 Cost:  5.367302 
Prediction:
 [[153.37442]
 [183.14278]
 [181.0273 ]
 [198.43153]
 [138.18811]]
80 Cost:  5.3452787 
Prediction:
 [[153.36693]
 [183.14798]
 [181.02507]
 [198.4294 ]
 [138.19537]]
90 Cost:  5.3233457 
Prediction:
 [[153.35942]
 [183.15315]
 [181.02283]
 [198.42726]
 [138.20262]]

830 Cost:  3.9840279 
Prediction:
 [[152.86003]
 [183.49942]
 [180.87477]
 [198.2815 ]
 [138.68967]]
840 Cost:  3.9692528 
Prediction:
 [[152.85399]
 [183.50363]
 [180.87299]
 [198.2797 ]
 [138.69565]]
850 Cost:  3.9545562 
Prediction:
 [[152.84793]
 [183.50784]
 [180.87122]
 [198.2779 ]
 [138.7016 ]]
860 Cost:  3.9399426 
Prediction:
 [[152.8419 ]
 [183.51202]
 [180.86942]
 [198.27608]
 [138.70752]]
870 Cost:  3.9253776 
Prediction:
 [[152.83588]
 [183.5162 ]
 [180.86765]
 [198.27426]
 [138.71344]]
880 Cost:  3.910933 
Prediction:
 [[152.82988]
 [183.52036]
 [180.86588]
 [198.27246]
 [138.71933]]
890 Cost:  3.89655 
Prediction:
 [[152.82391]
 [183.5245 ]
 [180.8641 ]
 [198.27068]
 [138.72522]]
900 Cost:  3.8822188 
Prediction:
 [[152.81793]
 [183.52866]
 [180.86234]
 [198.26889]
 [138.7311 ]]
910 Cost:  3.8679702 
Prediction:
 [[152.812  ]
 [183.53278]
 [180.86058]
 [198.26709]
 [138.73695]]
920 Cost:  3.8538022 
Prediction:
 [[152.80606]
 [183.53691]
 [180.85884]
 [198.26532]
 [138.7

1700 Cost:  2.9477174 
Prediction:
 [[152.39136]
 [183.82524]
 [180.73688]
 [198.1372 ]
 [139.15488]]
1710 Cost:  2.9383101 
Prediction:
 [[152.3866 ]
 [183.82855]
 [180.7355 ]
 [198.13571]
 [139.15965]]
1720 Cost:  2.9289384 
Prediction:
 [[152.38187]
 [183.83185]
 [180.7341 ]
 [198.13419]
 [139.1644 ]]
1730 Cost:  2.9196236 
Prediction:
 [[152.37714]
 [183.83513]
 [180.73273]
 [198.13266]
 [139.16913]]
1740 Cost:  2.9103637 
Prediction:
 [[152.37244]
 [183.83841]
 [180.73137]
 [198.13118]
 [139.17387]]
1750 Cost:  2.9011364 
Prediction:
 [[152.36775]
 [183.84167]
 [180.72998]
 [198.12967]
 [139.17859]]
1760 Cost:  2.8919673 
Prediction:
 [[152.36307]
 [183.84494]
 [180.7286 ]
 [198.12817]
 [139.18329]]
1770 Cost:  2.8828483 
Prediction:
 [[152.3584 ]
 [183.84819]
 [180.72725]
 [198.1267 ]
 [139.18799]]
1780 Cost:  2.8737743 
Prediction:
 [[152.35376]
 [183.85144]
 [180.72589]
 [198.12521]
 [139.19267]]
1790 Cost:  2.8647563 
Prediction:
 [[152.34912]
 [183.85468]
 [180.72455]
 [198.1